services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    volumes:
      - ./export:/app/export
      - ./seed.json:/app/seed.json
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: