"""add price and offers history

Revision ID: 2651f4aad1e8
Revises: 6ef0077b201d
Create Date: 2025-10-04 18:39:03.452252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2651f4aad1e8'
down_revision: Union[str, Sequence[str], None] = '6ef0077b201d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('products', sa.Column('offers_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'offers_history')
    op.drop_column('products', 'price_history')
    # ### end Alembic commands ###
