"""add sellers_count field

Revision ID: 6ef0077b201d
Revises: 8c34c8883f15
Create Date: 2025-10-04 18:10:37.684809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef0077b201d'
down_revision: Union[str, Sequence[str], None] = '8c34c8883f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sellers_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sellers_count')
    # ### end Alembic commands ###
